#!/usr/bin/env python3
"""
Script to add overflow="visible" to nested SVG elements in SVG files.

This fixes clipping issues in SVG files generated by tools like Excalidraw.
The root SVG is left unchanged; only nested/embedded <svg> elements are modified.
"""

import re
import sys
from pathlib import Path


def fix_nested_svg_overflow(file_path: Path) -> bool:
    """
    Add overflow="visible" to nested SVG elements in an SVG file.
    
    Args:
        file_path: Path to the SVG file
        
    Returns:
        True if the file was modified, False otherwise
    """
    content = file_path.read_text(encoding='utf-8')
    original_content = content
    
    # Pattern to match nested <svg> tags (not the first/root one)
    # This looks for <svg tags that are not at the very beginning of the file
    # We need to add overflow="visible" to nested SVGs that don't already have it
    
    # First, let's find all <svg tags that are not the root element
    # Root svg starts at the beginning, nested svgs appear elsewhere in the document
    
    def add_overflow_to_nested_svg(match: re.Match) -> str:
        """Add overflow="visible" to nested SVG tags that don't have it."""
        full_match = match.group(0)
        svg_start = match.group(1)  # <svg
        rest = match.group(2)       # Everything after <svg until >
        
        # Check if overflow attribute already exists
        if re.search(r'\boverflow\s*=', rest):
            return full_match
        
        # Add overflow="visible" before the closing >
        return f'{svg_start} overflow="visible"{rest}'
    
    # Pattern matches <svg followed by any attributes until >
    # This captures nested SVG elements (we'll skip the root)
    pattern = r'(<svg)([^>]*)(>|/>)'
    
    # For nested SVGs, we need to be careful not to modify the root
    # Strategy: Find all matches, but skip the first one if it's at position 0
    
    modified = False
    result = []
    last_end = 0
    
    for match in re.finditer(pattern, content):
        # Skip root SVG (first match at position 0)
        if match.start() == 0:
            result.append(content[last_end:match.end()])
            last_end = match.end()
            continue
        
        # Skip nested SVGs that already have overflow="visible"
        if 'overflow=' in match.group(0):
            result.append(content[last_end:match.end()])
            last_end = match.end()
            continue
        
        # Add overflow="visible" to nested SVG
        modified = True
        result.append(content[last_end:match.start()])
        svg_tag = match.group(0)
        # Insert overflow="visible" after <svg
        new_tag = re.sub(r'(<svg)', r'\1 overflow="visible"', svg_tag)
        result.append(new_tag)
        last_end = match.end()
    
    if modified:
        result.append(content[last_end:])
        new_content = ''.join(result)
        file_path.write_text(new_content, encoding='utf-8')
    
    return modified


def main():
    """Main entry point."""
    # Default directory if no argument provided
    target_dir = Path(__file__).parent if len(sys.argv) < 2 else Path(sys.argv[1])
    
    if not target_dir.is_dir():
        print(f"Error: {target_dir} is not a directory")
        sys.exit(1)
    
    # Find all SVG files in the target directory
    svg_files = list(target_dir.glob('*.svg'))
    
    if not svg_files:
        print(f"No SVG files found in {target_dir}")
        sys.exit(0)
    
    print(f"Processing {len(svg_files)} SVG file(s)...")
    
    modified_count = 0
    for svg_file in svg_files:
        if fix_nested_svg_overflow(svg_file):
            print(f"  ✓ {svg_file.name}")
            modified_count += 1
        else:
            print(f"  - {svg_file.name} (no changes needed)")
    
    print(f"\nModified {modified_count} of {len(svg_files)} file(s)")


if __name__ == '__main__':
    main()